### ISSUE TITLE
display problem on Windows OS

### ISSUE THREAD

**Issue by fzed51** [kahlan/kahlan#167]
Dans le [Reporter](https://github.com/kahlan/kahlan/blob/master/src/Reporter/Terminal.php#L93), les symboles `OK `et `ERR `ne s'affichent pas bien. Je travaille dans la console standard avec powershell et la chaine `\uxxxx` s'affiche.
Je propose de simplifier les symboles en utilisant des caractères ASCII ("V" pour `OK `et "X" pour `ERR`). Cela évitera tout problème d'affichage en fonction de l'encodage de la console.

Google translate :
In the [Reporter](https://github.com/kahlan/kahlan/blob/master/src/Reporter/Terminal.php#L93), the `OK `and `ERR `symbols are not displayed well. I work in the standard console with powershell and string `\uxxxx` appears.
I suggest to simplify the symbols using ASCII characters ("V" for `OK `and "X" for `ERR`). This will prevent any display problem according to the encoding of the console.

**Comment by samsonasik** [comment]
fixed at https://github.com/kahlan/kahlan/commit/f47303290cfcee3b358eb004eaa0154c22ed0c14 please try "kahlan/kahlan": "dev-dev" at yours.

**Comment by jails** [comment]
Thanks for the reporting, fixed in https://github.com/kahlan/kahlan/commit/f47303290cfcee3b358eb004eaa0154c22ed0c14

**Comment by jails** [comment]
I'll continue the discussion here @fzed51.
What do you mean by:
> You must use "\xE2\x9C\x94" to OK and "\xE2\x9C\x94" to ERR

Wasn't the previous behavior ?

**Comment by jails** [comment]
Does removing this [whole block](https://github.com/kahlan/kahlan/blob/master/src/Reporter/Terminal.php#L92-L96) solve your issue ?

**Comment by fzed51** [comment]
Non, la suppression du bloc de code ne résout pas le problème car il simplifie l'utilisation Kahlan sous Windows.
Les chaînes de caractère  "\xE2\x9C\x94" et "\xE2\x9C\x94" sont correctement interprétées par PHP. Le caractère d'echapent U n'est pas interprété par PHP.

Google translate :

No, the removal of the whole block does not solve the problem because it simplifies Kahlan use Windows.
Character strings "\xE2\x9C\x94" and "\xE2\x9C\x94" is correctly interpreted by PHP. The echapent U character is not interpreted by PHP.

**Comment by jails** [comment]
Sorry I'm not sure to get what you mean. "✓" === "\xE2\x9C\x94" and "✖" === "\xE2\x9C\x96" so if this characters are displayed correctly in powershell it should work.
Make sure you are testing the `dev` branch and feel free to reopen this issue again with a screenshot of the bugged output if not solved.

**Comment by jails** [comment]
Finally fixed in [3.0.1](https://github.com/kahlan/kahlan/commit/bfa163116a73a2916aef36492ccdb57496107901)

**Comment by fzed51** [comment]
J'étais en train de chercher une solution pour paramétrer l'utilisation des caractères UTF-8 et Unicode, mais l'utilisation des variables d'environnement est une très bonne idée. 
Beau travail.

Google translate:
I was in the process of seeking a solution to configure the use of UTF-8 and Unicode characters, but the use of the environment variables is a very good idea.
Nice work.

**Comment by jails** [comment]
Thanks buddy !
